- data-warehouse-integrations/snowflake.md
> Added permissions required for Rudderstack-s3 connection in Snowflake integrations
> Fix [#1]()
> Update snowflake docs to include rudderstack-s3 connection permissions

- administrators-guide/admin-troubleshooting-guide.md
> The  location of `recovery_data.json` file seems to be different than what's in docs. I'm running latest version of rudder, so updating the docs.
> Update location of recovery_data

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md
We should specify that the cookie is stored in the top-level domain before explaining that in an example
> Improve the identify call documentation

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.md
The data plane url parameter is confusing to me since it looks like it's meant to append a path to the hostname string, but it's not valid javascript and it's not totally clear what the intended modification here is. I think what you guys mean to show is that the path "/v1/batch" should be appended to the dataplane hostname URL, but I think it would be clearer to show that as a string template.
> Clarified dataplane url with template string
> Clarified data plane url variable

- data-warehouse-integrations/delta-lake.mdx
- rudderstack-api/test-api.mdx
> Updated Test API doc to include BigQuery Stream doc reference (that it is not supported).
> Updated Delta Lake docs to include FAQ re: reserved keywords.
> Fix [#1]()
> Documentation Updates

- postNavList.js
- sidebar.js
- stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> Removed JS SDK references from the event filtering documentation and the cross-reference in the JS SDK doc.  Also renamed Event Filtering to Client-side Event Filtering.
> Fix [#1]()
> Event Filtering Documentation Updates

- faqs.mdx
Took me way too long to find the data plane URL in the dashboard 😅
> Add specific place to find data plane URL for RudderStack Cloud in FAQ

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
> Updated the correct values for `maxRetryDelay` from 36000ms to 360000ms.
> Fix [#1]()
> maxRetryDelay Default Value Correction

- destinations/analytics/mixpanel.mdx
> Added clarification that RudderStack supports empty and null values as properties to mixpanel.
> Fix [#1]()
> Mixpanel doc update

- destinations/crm/salesforce.mdx
> Added information on mapping to `contactId` once a lead converts to a contact.
> [Salesforce contact information](https://www.notion.so/rudderstacks/Salesforce-Contact-Doc-Update-4608cc9f497b4d7e95c1050c8a35fc4d)
> Salesforce documentation update

- destinations/marketing/activecampaign.mdx
> Added information on the `eventData` mapping in the `track` call.
> [Active Campaign Event Discrepancy](https://www.notion.so/rudderstacks/Active-Campaign-Event-Discrepancy-946a432c7d574286818c855370a2e0cf)
> ActiveCampaign Documentation Updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> Added documentation for `withAutoCollectAdvertId` / `autoCollectAdvertId` for Android, Unity, React Native, Cordova, and Flutter docs.
> [Mobile SDK configuration for Advertising ID](https://www.notion.so/rudderstacks/Mobile-SDK-s-Configuration-for-Advertising-Id-8636b98c99df4873a6667374d2f1d0d5)
> Android SDK configuration for advertising IDs

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
> Corrected name for the Mailchimp destination to align with the reference in the transformer code.
> Destination name fix in JS SDK

- destinations/marketing/blueshift.mdx
> Removed group call section from the Blueshift documentation.
> [Blueshift remove `group` section](https://www.notion.so/rudderstacks/Remove-group-call-in-Blueshift-destination-185d3457d6db41e090fc9dab9d35d0e4)
> Blueshift documentation update - remove group call

- rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
> Added documentation of the Application Lifecycle Event spec.
> [Application Lifecycle Events documentation](https://www.notion.so/rudderstacks/Application-Lifecycle-Event-Spec-96fe23968561404eb4ccea328c6b9a86)
> Lifecycle Event Spec documentation

- data-governance/tracking-plans/index.mdx
- rudderstack-cloud/dashboard-overview.mdx
> Added information on warehouse destinations support for Tracking Plans.
> [Document: Tracking plans are currently for Warehouse destinations](https://www.notion.so/rudderstacks/Document-Tracking-plans-are-currently-for-Warehouse-destinations-8a8a865f4b064d15a9e314003496914e)
> Tracking Plans update

- rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> Added note mentioning Unity SDK doesn't support the Android platform for tracking app lifecycle events.
> [Application Lifecycle documentation update](https://www.notion.so/rudderstacks/Application-Lifecycle-documentation-update-47ab99f7eb9944e68a279375015bd7ba)
> Application Lifecycle Events Hotfix

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
> Removed info block and some minor cosmetic tweaks.
> [Remove info block in QSG: JS SDK](https://www.notion.so/rudderstacks/Remove-info-block-in-quick-start-guide-JS-SDK-6d462f9be51447a986199948362c347e)
> JS SDK Quick Start Guide update

- rudderstack-api/data-regulation-api.mdx
> Specified cloud mode destinations support and added list of destinations supported for `suppress_with_delete` request.
> [Data Regulation API doc updates](https://www.notion.so/rudderstacks/Data-Regulation-API-documentation-update-4fccbb22cb114219b0f337bc232ff8ed)
> Regulation API documentation updates

- data-warehouse-integrations/warehouse-schemas.mdx
> Added missing information on the `alias` call in the WH Schema documentation. Also, restructured the doc to move the table schemas first, before topics like clock skew consideration, etc.
> [`alias` table information in WH Schema doc](https://www.notion.so/rudderstacks/Add-aliases-table-info-in-Warehouse-Schema-doc-994a72d6f7a04695bd5290b7dad1c685)
> Alias information in Warehouse Schema documentation

- data-warehouse-integrations/google-bigquery.mdx
> BigQuery dedup information added to the documentation.
> [BigQuery documentation update - add information on deduplication method](https://www.notion.so/rudderstacks/BigQuery-documentation-update-add-information-on-deduplication-method-185c0f87725a47a5809c7dd0f1a5d255)
> BigQuery Update -  Deduplication Information

- docs/index.mdx
- src/@rocketseat/gatsby-theme-docs/components/Docs/index.js
Enables use of Gatsby Link component for internal linking. Includes one test link on the homepage- Docs team will migrate existing markdown-formatted links to use the much faster Link component
To test out the example link go to https://deploy-preview-585--rudderstack-docs-staging.netlify.app/#quick-start and compare clicking the Glossary link to other internal links
> N/A
> add Gatsby Link component to docs

- docs/get-started/cloud-vs-open-source.mdx
- docs/get-started/glossary.mdx
- docs/get-started/index.mdx
- docs/get-started/rudderstack-architecture.mdx
- uses Gatsby link for internal links
- copy edit
- use unicode for tables   ❌   ✅ 
Preview: 
- https://deploy-preview-586--rudderstack-docs-staging.netlify.app/get-started/cloud-vs-open-source/
- https://deploy-preview-586--rudderstack-docs-staging.netlify.app/get-started/rudderstack-architecture/
n/a
> Use gatsby link in OS vs. Cloud guide

- docs/destinations/crm/variance.mdx
Now that we support [alias](https://www.variance.com/changelog/updated-list-views#:~:text=Alias,the%20new%20ID.), here's an update to the docs calling it out.
NA
> feat: add Alias to Variance destination doc

- docs/destinations/marketing/customer.io.mdx
Alias call support added for Customer.io
https://www.notion.so/rudderstacks/CustomerIO-merge-functionality-update-47d0560653674e84a85008fb7925fa68
> Fix [#1]()
> Customer.io - Alias call

- gatsby-config.js
- package-lock.json
- package.json
Bumps RudderStack plugin to v1.1.1 and sets sdkURL option.
> Fix [#1]()
> Bump RudderStack plugin to v1.1.1

- docs/data-governance/index.mdx
- docs/data-governance/rudder-typer.mdx
- docs/data-governance/rudderstack-data-governance-api.mdx
- docs/data-governance/ruddertyper.mdx
- docs/data-governance/tracking-plans/index.mdx
- docs/identity-resolution.mdx
- docs/rudderstack-api/data-regulation-api.mdx
- docs/rudderstack-cloud/audit-logs.mdx
- docs/user-guides/administrators-guide/onelogin-sso.mdx
- docs/user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
> Standardize the pro/enterprise labels across all the relevant docs. Added missing labels for some docs on pro/enterprise features.
> [Pro/Enterprise labels standardization](https://www.notion.so/rudderstacks/Pro-Enterprise-labels-standardization-d99a2d94e0dc49b3870c4ff5d8bc6524)
> Standardize pro/enterprise labels across docs

- docs/identity-resolution.mdx
> Added note that ID res is supported only for BigQuery and Snowflake.
> [ID resolution doc updates](https://www.notion.so/rudderstacks/Identity-Resolution-support-call-out-in-the-docs-e3aa430bc14348cc8bc3abe502a0ab12)
> Identity Resolution doc updates

- docs/destinations/attribution/appsflyer.mdx
> Added iOS v2 device mode implementation steps.
> [AppsFlyer device mode updates](https://www.notion.so/rudderstacks/AppsFlyer-iOS-v2-device-mode-updates-2b0dffc9964949bab6bfb703796a1769)
> AppsFlyer iOS v2 device mode updates

- docs/destinations/webhooks.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> Updated steps for obtaining the advertising ID for iOS 14.
> Fixed 2 URLs in the webhook destination doc
> [iOS SDK AdvertisingID Documentation Update](https://www.notion.so/rudderstacks/iOS-SDK-AdvertisingID-Documentation-Update-3468781d00604a10b43b76a3a0b0dc29)
> [Broken URLs in Webhook destination](https://www.notion.so/rudderstacks/Broken-URLs-in-Webhook-destination-3956e365ede74f59a89f90c55b530218)
> iOS SDK Advertising ID documentation update

- docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
- docs/destinations/streaming-destinations/google-adwords-remarketing-list.mdx
> Removed rate limit note for 2 destinations:
- GA Remarketing Lists
- GA Enhanced Conversions
> [Remove rate limit note](https://www.notion.so/rudderstacks/Remove-rate-limit-note-for-GARL-and-GA-Enhanced-Conversions-edeca820c52e44d9b97843cabf189f41)
> Remove rate limit note for GA destinations

- docs/user-guides/how-to-guides/dynamic-destination-configuration.mdx
If I understood the request correctly, this PR removes the extraneous `message` objects from the example code. 
Additionally, we can clarify this page by replacing the instances of `message` with `event` once 
https://github.com/rudderlabs/rudder-transformer/pull/1289 is in production, as this usage can cause confusion for docs users.
> Dynamic destination config guide updates

- docs/event-spec/ecommerce-events-spec/index.mdx
> Added cross-reference links to specific sections in the E-commerce event spec landing page.
> [Cross-reference e-commerce spec pages](https://www.notion.so/rudderstacks/Cross-reference-links-to-E-commerce-event-spec-pages-dff8458669cb48f68fb48255d7a012ad)
> E-commerce spec landing page update

- docs/destinations/streaming-destinations/launchdarkly.mdx
Fixes typo in code block example. `privateAttributeNames` was misspelled.
N/A
> Fix typo in code block example

- docs/api/index.mdx
- docs/dashboard-guides/index.mdx
- docs/destinations/index.mdx
- docs/event-spec/index.mdx
- docs/features/index.mdx
- docs/get-started/index.mdx
- docs/resources/index.mdx
- docs/sources/reverse-etl/common-settings/index.mdx
- docs/sources/reverse-etl/features/index.mdx
- docs/user-guides/index.mdx
- gatsby-config.js
Standardizes our url format to exclude trailing slashes. This consistency will help with our SEO efforts.
- Removes trailing slash from sitemap and redirect urls.
- Configures Gatsby to no longer append trailing slashes.
> Remove trailing slash from urls

- docs/get-started/rudderstack-open-source/data-plane-setup/index.mdx
> Added warning note re: deploying multiple RudderStack nodes for running multiple warehouse services.
> Open Source multiple nodes warning

- docs/destinations/streaming-destinations/hubspot-v2.mdx
- docs/destinations/streaming-destinations/hubspot.mdx
- docs/sources/reverse-etl/faq.mdx
> Updated HubSpot docs specifying the necessary scopes for private apps auth to set up RETL connections.
> HubSpot doc update for RETL sources

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
> Added info on the `app_instance_id` parameter in the `identify` section.
> Added info on the `engagement_time_msec` and `session_id` parameters.
> Changed `items` mapping to RudderStack's `products` param.
> GA4 updates

- docs/dashboard-guides/permissions-management.mdx
- docs/dashboard-guides/user-management.mdx
- src/postNavList.js
- src/sidebar.js
> Split the permissions management doc into **user management** and **permissions management**.
> Added enterprise label for the permissions management doc
> Split permissions management doc

- gatsby-config.js
> Currently, the CDN url for the RS SDK is 404ing. This removes `/beta`, allowing for the url to resolve.
> Removes beta from the RS SDK cdn url

- docs/destinations/streaming-destinations/salesforce.mdx
Removes refs to salesforce flag
Preview: https://rudderstack-docs-7m3ilj8ml-rudder-stack.vercel.app/destinations/streaming-destinations/salesforce/
> Remove refs to salesforce flag

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
> Calls out GA4 UTM issue more prominently
Preview: https://rudderstack-docs-git-ga4-warning-rudder-stack.vercel.app/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode/
> Add stronger GA4 warning

- docs/dashboard-guides/personal-access-token.mdx
> Updated info block on the user permissions for creating and using the access token.
> Personal access token doc update

- docs/sources/event-streams/sdks/rudderstack-php-sdk.mdx
> Added descriptions for the `max_queue_size` and `batch_size` parameters in the initialization snippet.
> PHP SDK initialization snippet update

- docs/sources/event-streams/sdks/session-tracking/faq.mdx
- docs/sources/event-streams/sdks/session-tracking/index.mdx
- docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
- src/sidebar.js
> Updated session tracking docs to clarify how inactivity is handled.
> Separated manual session tracking from automatic to not have any scope for confusion.
Preview: [Here](https://rudderstack-docs-1cmeb2p4h-rudder-stack.vercel.app/sources/event-streams/sdks/session-tracking/)
> Session tracking docs optimization

- docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
> Updated Pinterest Ads cloud mode doc to add section on LDP support.
> Pinterest Ads - Added LDP support

- docs/features/data-governance/tracking-plans/index.mdx
> Context related to TP violations is sent to all the destinations, including warehouse and cloud destinations unless explicitly directed otherwise.
> Updated messaging in Tracking Plan docs

- docs/destinations/streaming-destinations/fb-pixel.mdx
> Updated the identify section stating only cloud mode support.
> Minor cosmetic enhancements to the doc
> Facebook Pixel identify call update

- docs/sources/event-streams/sdks/session-tracking/faq.mdx
- docs/sources/event-streams/sdks/session-tracking/index.mdx
> Simplified the section on the supported destinations for the SDKs' session tracking feature (mentioned support for cloud and warehouse destinations both instead of just Amplitude and Mixpanel)
> Update session tracking docs

- docs/user-guides/administrators-guide/bucket-configuration-settings.mdx
> Added `getObject` action in configuring bucket permissions for event backup and replay
> Minor content cleanup
> S3 permissions update

- docs/destinations/streaming-destinations/fb-pixel.mdx
> Add a note that `revenue` is a required field for the events mapped to the `Purchase` standard event.
Context: [This Slack thread](https://rudderstack.slack.com/archives/C01E4PLB135/p1675426990331889?thread_ts=1675257762.310809&cid=C01E4PLB135)
> Facebook Pixel doc fix

- docs/api/data-regulation-api.mdx
> We no longer deletion from all the destinations, if no `destinationId` is specified. It is a must have field when regulation type is `suppress_with_delete` & we throw error, if it is not present.
- [x ] Documentation update
> chore: fix regulation API doc for destinationIds
