rudderlabs/rudderstack-docs

- destinations/salesforce.md
> Added Salesforce ERROR in FAQ

- destinations/braze.md
> Braze group implementation

- destinations/userlist.md
This pull requests adds destination documentation for [Userlist](https://userlist.com)
> Adds documentation for the Userlist destination

- destinations/userlist.md
I just noticed that we forgot to mention our website and support email address. I added these in this change. Thanks for the smooth collaboration on this one!
> Adds Userlist link and support email address.

- destinations/amplitude.md
> Amplitude: revenue for cloud mode

- destinations/zendesk.md
> Update zen desk.

- destinations/appcues.md
- rudderstack-sdk-integration-guides/sdk-faqs.md
> Appcues Cloud Mode Documentation

- destinations/appcenter.md
>Added rudderstack repository in build.gradle 
> Fix [#1]()
> Updated Dependencies in build.gradle

- destinations/appcues.md
> Minor Modifications

- destinations/appsflyer.md
> Added support for af_revenue for Order Completed event

- SUMMARY.md
- how-to-guides/README.md
- how-to-guides/integrate-rudderstack-with-a-gatsby-site.md
> Added Gatsby plugin docs to Rudderstack docs. 
**? I don't know how to test this locally, and today didn't have the time. I think everything should work great though.**
> Add doc page: "How to Integrate Rudderstack with a Gatsby Website."

- rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> Updated Flutter SDK Documentation

- destinations/appcenter.md
> Added React Native Device Mode support for Appcenter

- destinations/appcenter.md
> Updated Appcenter RN Mode Documentation

- destinations/appcenter.md
> Added Documentation for Opt-in And Opt-out of Appcenter

- destinations/amplitude.md
> Updated AM Config Details

- destinations/clevertap.md
> Added documentation of clevertap android, iOS & RN device modes

- destinations/clevertap.md
> Updated Connection Modes of Clevertap

- destinations/clevertap.md
> Added RN CleverTap Documentation

- rudderstack-api-spec/pixel-api-spec.md
> Add pixel api spec

- destinations/customer.io.md
> Customer.io : docs edit for event name trim

- rudderstack-sdk-integration-guides/rudderstack-java-sdk.md
> Maven Repo details added

- connections.md
Currently, there is a repetition of the word 'from' in this sentence which creates confusion. I have attempted to make it more concise and readable.
Thanks
> Update 'Source' hint to make it more readable.

- destinations/gainsight.md
> update gainsight doc missing part

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Added Docs for RudderOption Support in React Native SDK 

- destinations/analytics/kubit.md
> Update tag line and clarify integration modes.

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> Added docs for Enabling/Disabling specific Integrations in Flutter SDK

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Added Info for deviceModeCallBackThreshold config

- destinations/continuous-integration/appcenter.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Removed deviceModeCallBackThreshold from RN SDK

- destinations/data-ingestion/google-pub-sub.md
> update and correct pubsub doc

- destinations/analytics/Adobe Analytics/setting-up-adobe-analytics-in-rudderstack.md
- destinations/analytics/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.md
> added proxy url for loading aa sdks

- destinations/data-ingestion/google-pub-sub.md
> add dotted key example

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> Added Info Tag About Flutter Null Safety in Flutter docs

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Fixed Tabs on Android and iOS FAQ's

- destinations/analytics/heap.io.md
> added for web native sdk

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Added docs for accessing context by promises in RN SDK

- destinations/advertising/fb_custom_audience.md
> Update Facebook Custom Audience Documentation

- destinations/attribution/appsflyer.md
> Added Docs for Retrieving AppsFlyerId on RN

- destinations/analytics/Adobe Analytics/adobe-analytics-heartbeat.md
- destinations/analytics/Adobe Analytics/adobe-analytics-mobile-device-mode.md
> Adobe Analytics docs for Adobe device mode

- SUMMARY.md
- destinations/analytics/adobe-analytics/README.md
- destinations/analytics/adobe-analytics/adobe-analytics-mobile-device-mode.md
> Added Adobe Mobile Docs in Summary and Readme

- destinations/analytics/lytics.md
> added support for name and few other changes Lytics

- destinations/advertising/fb_custom_audience.md
> Fb Custom Audience Minor changes

- destinations/advertising/fb_custom_audience.md
> Minor changes 2

- destinations/attribution/appsflyer.md
> Updated AppsFlyer Docs

- rudderstack-api/rudderstack-spec/common-fields.md
> added details for campaing in api

- destinations/braze.md
> Fixed Braze Destination Docs

- destinations/analytics/adobe-analytics/adobe-analytics-heartbeat.md
- destinations/analytics/adobe-analytics/adobe-analytics-mobile-device-mode.md
> Adobe iOS device mode

- destinations/analytics/adobe-analytics/adobe-analytics-mobile-device-mode.md
> Improved `ADBMobileConfig` file uploading process

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Response code test

- destinations/marketing/clevertap.md
> Updated Syntaxes for Android Device Mode Integration of Clevertap

- destinations/advertising/criteo.md
> Criteo: update regarding extra data

- warehouse-actions/amazon-s3.md
> add extra information on parquet files and s3 actions permission

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> Added Syntaxes for Initializing Rudder Logger of Flutter SDK

- destinations/advertising/facebook-app-events.md
> Enhanced Docs Of App Events

- destinations/marketing/drip/drip-cloud-mode.md
- destinations/marketing/drip/drip-web-device-mode.md
> Minor documentation update - IMO, these titles will be clear to the reader and since these are independent pages, some repetition shouldn't matter that much.
> Fix [#1]()
> Drip doc update

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
> Added Docs for Custom Device Mode Destination Support in Android

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Added Docs for Custom Device Mode Destination Support in iOS

- rudderstack-api/api-specification/rudderstack-spec/common-fields.md
> Fixed common-fields.md

- destinations/marketing/ometria.md
> add event_id info in ometria

- destinations/marketing/qualtrics-website-feedback.md
> Qualtrics Android and iOS device mode docs - Ready from Dev

- rudderstack-api/api-specification/rudderstack-spec/identify.md
> Fixed identify.md

- destinations/marketing/ometria.md
> minor update in ometria doc

- destinations/attribution/branchio.md
> Updated Version for iOS Branch Device Mode

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Added Docs for GDPR Support across Native Mobile SDK's

- destinations/marketing/qualtrics.md
> Updated importing statement for Qualtrics docs

- destinations/attribution/branchio.md
> Branch - revamp update event-mapping

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md
> JS SDK clarification re: IP address

- destinations/marketing/clevertap.md
> Clevertap added new feature

- faqs.md
> Consolidate RudderStack Cloud questions

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Added Docs for GDPR Support across Hybrid Mobile SDK's

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.md
> Removed GDPR docs from Mobile SDK's

- README.md
> Fixed Follow Us link titles

- destinations/analytics/aws-personalize.md
> updated personalize doc for compatibility

- README.md
> Remove asterisks

- README.md
> Update Slack community channel link

- destinations/attribution/appsflyer.md
> Updated AppsFlyer Docs on Retreiving AppsFlyer Id on Android and RN

- warehouse-actions/snowflake.md
> Update user permissions to include detailed steps

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/README.md
> Change code whitespace

- destinations/error-reporting/sentry.md
> minor update

- destinations/error-reporting/sentry.md
> Sentry Doc update

- warehouse-actions/amazon-redshift.md
- warehouse-actions/google-bigquery.md
- warehouse-actions/postgresql.md
> User permissions for setting up Warehouse Actions sources

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Opt-out doc for Mobile-SDK's

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Add SKAdNetwork FAQ

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> GDPR FAQs for Android / iOS SDKs

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> Updated Flutter SDK version to 1.0.5

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/README.md
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.md
> Implemented correct GDPR version.

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk.mdx
> Highlighted tvOS Support in iOS SDK Docs

- destinations/analytics/amplitude.mdx
- destinations/marketing/braze.mdx
> Added Docs for Amplitude and Braze for RN Device Mode

- destinations/analytics/firebase.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
- warehouse-actions/visual-data-mapper.mdx
> This PR fixes some discrepancies found in the following docs:
- JavaScript SDK
- Firebase destination
- VDM (Visual Data Mapper)
These discrepancies include:
- Formatting issues
- Broken URLs
> Fix [#1]()
> Documentation fixes

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
> Fixed the issue highlighted here: https://github.com/rudderlabs/rudder-sdk-js/issues/232
> Fix [#1]()
> Updated code snippet to fix callback position

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
> JS SDK Version Migration guide updates

- data-governance/rudderstack-data-governance-api.mdx
- data-warehouse-integrations/identity-resolution-in-rudderstack.mdx
- rudderstack-api/user-suppression.mdx
- user-guides/administrators-guide/okta-sso.mdx
- user-guides/administrators-guide/onelogin-sso.mdx
> Ported all the changes from this PR: https://github.com/rudderlabs/rudderstack-docs/pull/258
> Fix [#1]()
> Enterprise plan badges

- destinations/analytics/fullstory.mdx
> FullStory code hotfix

- destinations/analytics/fullstory.mdx
> FullStory tab formatting fix

- user-guides/administrators-guide/alerting.mdx
Small typo in documentation
> Fix [#1]()
> Fix typo in alerting.mdx

- postNavList.js
- sidebar.js
> Updated doc structure to separate RudderStack Open Source and RudderStack Cloud.
> Fix [#1]()
> Updated doc structure

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
> Android SDK updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
> Added Documentation for using Rudder Android SDK version on Api level less than 20

- postNavList.js
- sidebar.js
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/js-sdk-faqs.mdx
> Update JS SDK FAQs title

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> Updated Device Token docs of Mobile SDK's

- rudderstack-api/api-specification/rudderstack-spec/common-fields.mdx
- rudderstack-api/api-specification/rudderstack-spec/page.mdx
- rudderstack-api/api-specification/rudderstack-spec/screen.mdx
- rudderstack-api/api-specification/rudderstack-spec/track.mdx
> Minor URL fixes.
> Fix [#1]()
> URL updates to the RudderStack API spec docs

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> Minor doc fixes.
> Fix [#1]()
> Minor doc fixes - devicetoken

- warehouse-actions/visual-data-mapper.mdx
> Updated doc to include Iterable as a supported destination.
> Fix [#1]()
> VDM doc update

- destinations/analytics/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
- destinations/analytics/firebase.mdx
- destinations/continuous-integration/appcenter.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- Added minimum support version info for Cordova-SDK.
- Added docs to initialise the AppCenter device mode.
- Added Firebase dependencies.
- Added Adobe mobile device mode support (Previously it was missing).
> Fix [#1]()
> Cordova docs

- destinations/attribution/appsflyer.mdx
- destinations/continuous-integration/appcenter.mdx
- Implemented Cordova AppsFlyer device mode docs
- Corrected the AppCenter plugin name
> Fix [#1]()
> Implemented Cordova AppsFlyer docs

- destinations/analytics/google-analytics-ga.mdx
> Updated GA doc to include clarification re: Optimize and how it will be used.
> Fix [#1]()
> GA documentation update

- rudderstack-api/test-api.mdx
> Content updates for the Test API. Also incorporated the feedback shared by various team members.
> Fix [#1]()
> Test API updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
> Updated Flutter documentation to 1.2 and added note for the older documentation.
> Fix [#1]()
> Flutter v1.2 Documentation Update

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
> Updated the JS SDK docs to include mention of the secureCookie flag in the `load` section.
> Fix [#1]()
> Secure Cookie flag in JS SDK

- destinations/advertising/fb-pixel.mdx
> Updated the page section to specify that the page properties and the event ID are now automatically passed downstream.
> Fix [#1]()
> Facebook Pixel Documentation Updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> Added documentation for background run time on iOS

- transformations/index.mdx
> Library supported syntax

- data-warehouse-integrations/delta-lake.mdx
> Delta Lake Doc Update

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> Fixed function name and combined the success tips to make them look less repetitive.
> Fix [#1]()
> iOS SDK Documentation updates

- destinations/advertising/fb-custom-audience.mdx
> Fixed documentation for Facebook Custom Audience, wherein some changes of a merged PR were missing.
> Fix [#1]()
> Custom Audience Documentation fix

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
> Suggested changes. If they look good - will implement across the other docs as well!
> Fix [#1]()
> Chromecast Android Doc Update

- destinations/attribution/branchio.mdx
> Fixed the documentation missing in the Branch PR merged before.
> Fix [#1]()
> Branch Missing Updates Fix

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- Provided doc for the Chromecast Android, iOS and Web.
> Fix [#1]()
> Chromecast doc for Android, iOS and Web

- warehouse-actions/airflow-provider.mdx
> Update airflow provider

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
> Fixed typos/image URLs for various SDK docs.
> Fix [#1]()
> SDK doc fixes

- destinations/streaming-platforms/index.mdx
> Fix: broken bigquery stream link

- user-guides/how-to-guides/dynamic-destination-configuration.mdx
> DynamicConfigDocAdd: Added few informations

- Destination_Template.mdx
> Made changes to the destination template.
> Fix [#1]()
> Destination template updates

- faqs.mdx
> Updated FAQs to replace incorrect link and remove deprecated/outdated content.
> Fix [#1]()
> FAQs update

- destinations/analytics/amplitude.mdx
- destinations/marketing/activecampaign.mdx
> For ActiveCampaign, Amplitude.
> Fix [#1]()
> Identify call doc fixes

- destinations/analytics/amplitude.mdx
> Add: session id faq

- destinations/analytics/statsig.mdx
> Documentation for the Statsig integration
> Fix [#1]()
> Adding documentation for Statsig

- rudderstack-api/http-api.mdx
> Removed content related to the unsupported `batch` fields.
> Fix [#1]()
> Batch Request Update

- rudderstack-api/data-regulation-api.mdx
Separated the suppression and suppression with delete requests for better clarity.
> Fix [#1]()
> Data Regulation API updates

- destinations/advertising/facebook-app-events.mdx
> Updated App Events doc to specify identify support only in mobile device mode.
> Fix [#1]()
> App Events update

- stream-sources/rudderstack-sdk-integration-guides/event-filtering.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
> Reverted changes for the JS SDK.
> Fix [#1]()
> Event Filtering Doc Updates

- destinations/marketing/customer.io.mdx
> Updated the documentation to include information on unsubscribing users in Customer.io via `identify`. 
> Fix [#1]()
> Customer.io Update: Unsubscribing Users

- user-guides/administrators-guide/index.mdx
> Remove: home button

- destinations/marketing/activecampaign.mdx
> Updates to the `identify` call to include `firstName` and `lastName`.
> Fix [#1]()
> ActiveCampaign Updates

- data-governance/index.mdx
> Refreshed content for the Data Governance API.
> Fix [#1]()
> Data Governance Updates

- destinations/crm/salesforce.mdx
> Corrected the Salesforce identify call.
> Fix [#1]()
> Salesforce Identify Call Correction

- data-warehouse-integrations/amazon-redshift.mdx
- data-warehouse-integrations/azure-datalake.mdx
- data-warehouse-integrations/azure-synapse.mdx
- data-warehouse-integrations/clickhouse.mdx
- data-warehouse-integrations/delta-lake.mdx
- data-warehouse-integrations/gcs-datalake.mdx
- data-warehouse-integrations/google-bigquery.mdx
- data-warehouse-integrations/microsoft-sql-server.mdx
- data-warehouse-integrations/postgresql.mdx
- data-warehouse-integrations/s3-datalake.mdx
- data-warehouse-integrations/warehouse-faqs.mdx
> Updated the whitelisted IPs for all the relevant Warehouse Destinations docs, including the IPs for the EU cluster.
> Fix [#1]()
> Updated Whitelisted IPs

- user-guides/how-to-guides/how-to-submit-an-integration-pull-request.mdx
> Integration PR Guide Updates

- destinations/advertising/pinterest-ads.mdx
> Updated event mapping

- postNavList.js
- sidebar.js
> Candu and TikTok ads

- destinations/marketing/clevertap.mdx
> Screen support for device mode (note removed).
> Fix [#1]()
> CleverTap doc updates

- destinations/attribution/branchio.mdx
- destinations/business-messaging/intercom.mdx
- destinations/continuous-integration/appcenter.mdx
- destinations/marketing/qualtrics.mdx
> minSdk for device mode integrations

- rudderstack-api/http-api.mdx
> Timestamp format info update 

- destinations/webhooks.mdx
> Update: webhooks

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> Added support for `group` and `alias`, cleaned up some tables.
> Fix [#1]()
> React Native SDK documentation update

- destinations/storage-platforms/minio.mdx
MinIO license changed last year reflecting the updated license for the project.
> update the licensing for MinIO

- cloud-extract-sources/google-search-console.mdx
- cloud-extract-sources/intercom-v2.mdx
- cloud-extract-sources/pipedrive.mdx
- connections/adding-source-and-destination-rudderstack.mdx
- data-governance/index.mdx
- data-warehouse-integrations/index.mdx
- destinations/advertising/facebook-app-events.mdx
- destinations/advertising/tiktok-ads.mdx
- destinations/analytics/aws-personalize.mdx
- destinations/analytics/kubit.mdx
- destinations/continuous-integration/appcenter.mdx
- faqs.mdx
- get-started/dashboard-overview/audit-logs.mdx
- glossary.mdx
- transformations/rudderstack-transformation-api.mdx
- user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
> Updated him/his/her to them/their along with some other quick, high-level changes.
> Fix [#1]()
> Gender-neutral pronoun usage

- data-warehouse-integrations/delta-lake.mdx
> Minor doc updates re: Spark configuration.
> Fix [#1]()
> Delta Lake documentation updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
> Added documentation for the .NET SDK logging feature.
> Fix [#1]()
> Logging support for .NET SDK

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
> Added flush() documentation for the Python and .NET SDKs.
> Fix [#1]()
> Flush support for Python and .NET SDK

- destinations/analytics/mixpanel.mdx
> Updated callout to remove reference to server-side track call.
> Fix [#1]()
> Mixpanel bug fix

- destinations/analytics/firebase.mdx
> Firebase hotfix re: iOS device mode issue
> Fix [#1]()
> Firebase Hotfix

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> Added documentation for setAnonymousID().
> Fix [#1]()
> Setting anonymous ID in Unity SDK

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> Minor updates to .NET and Unity SDK documentation.
> Fix [#1]()
> Minor doc fixes

- data-governance/index.mdx
> Change: data governance api video start time

- rudderstack-api/api-specification/rudderstack-spec/alias.mdx
- Change header from "page" to "alias"
- Change order of fields to align with method `alias(to, from)`
> Update: alias

- stream-sources/shopify.mdx
> Updated typos and some descriptions.
> Fix [#1]()
> Shopify minor doc fixes

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
> JS architecture update in NPM

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/consent-managers/onetrust.mdx
Updated code snippet and note to capture user consent
> Fix [#1]()
> Consent manager doc update

- connections/models.mdx
- postNavList.js
- sidebar.js
- warehouse-actions/setting-connections-using-models.mdx
> Content and sidebar updates for custom models.
> Fix [#1]()
> Custom Models - content and sidebar updates

- data-warehouse-integrations/warehouse-schemas.mdx
- rudderstack-api/api-specification/rudderstack-spec/common-fields.mdx
- rudderstack-api/http-api.mdx
> Improved documentation around timestamps and clock skew consideration.
> Fix [#1]()
> Timestamp Docs Enhancement

- event-replay.mdx
> Event Replay feature

- warehouse-actions/features/airflow-provider.mdx
- warehouse-actions/features/visual-data-mapper.mdx
> Updated image URLs since the directories were changed.
> Fix [#1]()
> Warehouse Actions features - Image URL fixes

- destinations/advertising/google-adwords-remarketing-list.mdx
> Code formatting updates.
> Fix [#1]()
> AdWords Remarketing List code formatting

- destinations/advertising/google-adwords-remarketing-list.mdx
> correct example payload
> Fix [#1]()
> Google Ads Remarketing Lists: hotfix - correct example payload

- connections/models.mdx
- postNavList.js
- sidebar.js
- warehouse-actions/features/index.mdx
- warehouse-actions/features/setting-connections-using-models.mdx
Topic rename and minor structural and formatting changes
> Fix [#1]()
> Models topic rename and formatting changes

- destinations/analytics/mixpanel.mdx
Added a section to ignore last seen property update
> Fix [#1]()
> Ignore 'Last seen' property

- get-started/live-events.mdx
> Added note that the live events feature are applicable only for cloud mode destinations.
> Fix [#1]()
> Live events update

- destinations/advertising/google-adwords-remarketing-list.mdx
> Updated documentation to remove the note regarding customer ID and also updated the audiencelist event structure to support both addition and deletion.
> Fix [#1]()
> Google Ads Remarketing Lists Update

- user-guides/migration-guides/rudderstack-migration-guide.mdx
> Added a new tab for the React Native SDK implementation.
[React Native implementation for Segment to RudderStack migration](https://www.notion.so/rudderstacks/React-Native-implementation-for-Segment-to-RudderStack-migration-e292ff76ef384f7db6ab8d51175654df)
> React Native SDK implementation in Segment-RudderStack migration guide

- warehouse-actions/features/setting-up-connections-using-models.mdx
> Updated URL
> Add a link to the related Notion ticket (for internal use only).
> URL fix in Models documentation

- user-guides/migration-guides/rudderstack-migration-guide.mdx
> Updated fixes for contact section in migration guide.
> Fix [#1]()
> Migration guide hotfix

- warehouse-actions/amazon-s3.mdx
> Updated S3 documentation and the associated resources.
> Fix [#1]()
> S3 Documentation Revamp

- warehouse-actions/faq.mdx
- warehouse-actions/index.mdx
> Updated the landing page and moved FAQs as a separate page.
> Fix [#1]()
> Warehouse Actions landing page

- warehouse-actions/faq.mdx
> Added missing FAQ and fixed a broken image URL
> Fix [#1]()
> Warehouse Actions FAQ update

- destinations/business-messaging/intercom.mdx
Specified support for mobile cloud mode
> Fix [#1]()
> Intercom Update

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
Added code snippet to track screen recording changes
> Fix [#1]()
> Track screen recording

- destinations/marketing/moengage.mdx
Added RudderStack to MoEngage mappings
> Fix [#1]()
> RudderStack to MoEngage mappings

- destinations/advertising/fb-pixel.mdx
Updated data type for category field
> Fix [#1]()
> Data type for category field

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/quick-start-guide.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide.mdx
Added new section for updating version using NPM
> Fix [#1]()
> Update JS SDK using NPM and browser versions update

- data-governance/rudder-typer.mdx
- data-governance/ruddertyper.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
- user-guides/how-to-guides/custom-domains.mdx
- user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-angular-integration.mdx
- user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-hugo-integration.mdx
- user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-jekyll-integration.mdx
- user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
- user-guides/migration-guides/rudderstack-migration-guide.mdx
Updated links for JS SDK v1 to v1.1 and added info box to version migration guide 
> Fix [#1]()
> Updated JS SDK v1 to v1.1

- stream-sources/shopify.mdx
Removed beta badge from the doc
> Fix [#1]()
> Shopify remove beta badge 

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
> Updated Flutter v2 documentation to update `screen` call parameters and code snippet.
> [Flutter v2 Screen Update](https://www.notion.so/rudderstacks/Flutter-v2-screen-call-update-4154100cfd9444d88ecdbee554ddd924)
> Flutter v2 Screen Updates

- destinations/marketing/moengage.mdx
Added a tab for steps to add MoEngage to React Native app
> Fix [#1]()
> Add MoEngage to React Native app

- destinations/analytics/google-analytics-ga.mdx
Added information about measurement protocol parameters
> Fix [#1]()
> Measurement protocol parameters for GA

- destinations/advertising/facebook-app-events.mdx
Added page call support
> Fix [#1]()
> Page call support added for FB App event 

- rudderstack-api/data-regulation-api.mdx
> Updated enterprise plan badge layout.
> Add a link to the related Notion ticket (internal use only).
> Badge layout update

- destinations/advertising/index.mdx
> Updated Google Ads destination path.
> Google Ads path update in the main page.

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v2.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-rust-sdk.mdx
Added version badges for all SDK docs
> Fix [#1]()
> Version badges for all SDK docs

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Added description and sample code for identify call
> Fix [#1]()
> Added pre-defined API for traits in Unity

- destinations/analytics/amplitude.mdx
Added new residency server setting
> Fix [#1]()
> Residency server setting in Amplitude

- destinations/advertising/fb-pixel.mdx
Updated event ID details 
> Fix [#1]()
> FB Pixel Event ID details 

- reverse-etl/features/visual-data-mapper.mdx
Updated the list of VDM supported destination
> Fix [#1]()
> Updated VDM supported destinations

- destinations/advertising/dcm-floodlight.mdx
Removed web support for DCM cloud mode
> Fix [#1]()
> Removed web support for DCM cloud mode

- destinations/attribution/appsflyer.mdx
> Added React Native and Android device mode updates for AppsFlyer.
> [Appsflyer React Native and Android Device Mode Changes](https://www.notion.so/rudderstacks/Appsflyer-React-Native-and-Android-Device-Mode-Changes-8e79fd1ccda94c21afc13804a8eeca85)
> AppsFlyer device mode updates

- destinations/advertising/snap-pixel.mdx
Updated e-commerce events for Snap Pixel
> Fix [#1]()
>  Snap Pixel: Updated e-commerce events 

- sidebar.js
> Alphabetical ordering of the destinations in the sidebar.
> [Reorder integrations in the sidebar](https://www.notion.so/rudderstacks/Reorder-integrations-in-the-sidebar-c5cb5c62dd594f6e80bbbf8605b7013c)
> Sidebar updates

- destinations/advertising/google-adwords-enhanced-conversions.mdx
- destinations/advertising/google-adwords-remarketing-list.mdx
> Added the permissions FAQ for Enhanced Conversions docs
> Enhanced Conversions FAQ

- destinations/advertising/dcm-floodlight.mdx
Added info box for sending device specific information for DCM Floodlight
> Fix [#1]()
> Device specific information for DCM Floodlight

- rudderstack-cloud/index.mdx
- user-guides/migration-guides/home.mdx
> Updated home page content
> [Getting Started revamp](https://www.notion.so/rudderstacks/Getting-Started-revamp-a476e3443530491ba2badd6eaa09bcc9)
> Home page updates

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
- user-guides/migration-guides/rudderstack-migration-guide.mdx
Added anonymousIdOptions in JS SDK
> Fix [#1]()
>  anonymousIdOptions added in JS SDK

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Updated reset method JS SDK to clear anonymousId
> Fix [#1]()
> JS SDK Reset method update 

- destinations/attribution/appsflyer.mdx
> Updated Appsflyer Device Mode related information

- destinations/attribution/appsflyer.mdx
> Formatting fix

- rudderstack-api/api-specification/application-lifecycle-events-spec.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
Updated info for lifecycle events
> Fix [#1]()
> Updated info for lifecycle events

- destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> formatting

- destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
- destinations/analytics/google-analytics-4/index.mdx
- destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
GA4 formatting fix
> Fix [#1]()
> GA4 formatting fix

- destinations/attribution/appsflyer.mdx
> Added documentation for first_purchase event in Appsflyer destination

- rudderstack-open-source/control-plane-lite.mdx
- rudderstack-open-source/installing-and-setting-up-rudderstack/developer-machine-setup.mdx
- rudderstack-open-source/installing-and-setting-up-rudderstack/sending-test-events.mdx
Update versions of go, nodejs, postgres.
Send data script is provided out of the box.
> Fix [#1]()
> feat(data plane setup): send events script out of the box, bump versions

- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
Added cookie and note to improve visibility
> Fix [#1]()
> Added cookie

- user-guides/administrators-guide/okta-sso.mdx
> Updated Okta SSO docs with the note re: IdP auth support.
> [Okta SSO Documentation update](https://www.notion.so/rudderstacks/Okta-SSO-Documentation-update-42ceee7266ef4dfa9e9f6914cab82044)
> Okta SSO documentation updates

- reverse-etl/google-bigquery.mdx
- stream-sources/customerio.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
This PR adds some aliases to a few mdx front matter so we can test to make sure that Algolia is picking them up.
> N/A
> Add aliases to mdx frontmatter for Algolia testing

- docs/data-warehouse-integrations/snowflake.mdx
> Added an example and note related to the AWS account locators for some regions.
> [Snowflake destination updates](https://www.notion.so/rudderstacks/Update-information-re-AWS-account-locator-in-Snowflake-docs-2e531483e5854c199a98060601d7b8cf)
> Snowflake documentation updates

- docs/destinations/analytics/amplitude.mdx
Added a subheading for sending event_id 
> Fix [#1]()
> Amplitude: Send event_id

- gatsby-config.js
- src/utils/docs-algolia.js
Update Algolia search index is API key is present.
> Conditionally add search indexing to builds

- docs/data-governance/tracking-plans/index.mdx
- docs/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
> Updated tracking plans documentation re: violation context and supported calls.
> [Update tracking plan documentation about the violation context](https://www.notion.so/rudderstacks/Update-tracking-plan-documentation-about-the-violation-context-d016930157a943ee9d7cd4fe3d8de56e)
> [Bug in Tracking Plan docs - update what calls are supported](https://www.notion.so/rudderstacks/Bug-in-Tracking-Plan-docs-update-what-calls-are-supported-cb79981c47ba41c6862632f4f13313cc)
> Tracking Plans updates

- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/macos.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
- src/postNavList.js
- src/sidebar.js
> Rebasing the older branch was causing some issues so moved the doc in a new PR. > Incorporated all suggestions made by @pallabmaiti as listed in [this] PR.
> [Swift migration doc](https://www.notion.so/rudderstacks/Documentation-Update-Swift-SDK-c7e6e635bbdb4c91970926b20a3c8274)
> Swift SDK migration

- gatsby-config.js
- package.json
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202285249847354
> Added favicon

- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/flushing-events-periodically.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
- src/sidebar.js
Added support for flush API in Android, iOS and React Native SDK docs
> Fix [#1]()
> Flush API update in mobile SDK

- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
Added steps for using NPM package of JavaScript SDK in Next.js app
https://www.notion.so/rudderstacks/Doc-update-for-next-js-app-using-npm-package-of-the-JS-SDK-86814f731c714fb4a715e6cb8000a1e9
> Fix [#1]()
> Next.js: Use NPM package of JavaScript SDK

- docs/destinations/analytics/firebase.mdx
> Firebase device mode updates for iOS SDK v2
> [Firebase device mode updates for iOS v2](https://www.notion.so/rudderstacks/Firebase-device-mode-destination-updates-64d8a6f253da4abda5c04766efc6d730)
> Firebase device mode updates for iOS SDK v2

- docs/data-warehouse-integrations/azure-synapse.mdx
- docs/data-warehouse-integrations/gcs-datalake.mdx
- docs/data-warehouse-integrations/snowflake.mdx
Added some missing details for  GCP bucket (data lake), Snowflake and Azure Synapse
https://www.notion.so/rudderstacks/Issues-in-warehouse-specific-configurations-in-docs-9151ac68e8764e20a8c8c64a85a69e92
> Fix [#1]()
> Warehouse-specific configuration improvements

- docs/data-warehouse-integrations/snowflake.mdx
- docs/user-guides/how-to-guides/custom-domains.mdx
> Updated custom domains doc with GCP load balancer-specific settings.
> [Custom domains update](https://www.notion.so/rudderstacks/Custom-Domains-doc-update-07b88a86c96541239583ed9edb970044)
> Custom Domains documentation updates

- docs/destinations/business-messaging/intercom.mdx
> Added information on the identity verification feature of Intercom.
> [Intercom user_hash support](https://www.notion.so/rudderstacks/Intercom-device-mode-user_hash-support-10c49efc4a4e4fe3b2a0d29df2d423d0)
> Intercom documentation updates

- src/@rocketseat/gatsby-theme-docs/components/SEO.js
Updates Structured Data scripts to match dotcom's structured data
> Fix [#1]()
> Update structured data

- docs/data-warehouse-integrations/warehouse-faqs.mdx
> FAQ hotfix.
> [Warehouse FAQ hotfix](https://www.notion.so/rudderstacks/Warehouse-FAQ-hotfix-da7836ab035a43e28bd657e933ae0afd)
> Warehouse FAQ update

- netlify.toml
> try new redirect pattern

- netlify.toml
> Redirect pattern

- docs/stream-sources/shopify.mdx
Shopify best practices
> Fix [#1]()
> Shopify best practices

- docs/destinations/analytics/amplitude.mdx
Amplitude - iOS v2 device mode update
> Fix [#1]()
> Amplitude - iOS v2 device mode update

- netlify.toml
Removed 'docs' from the 'from' redirects
> Fix [#1]()
> Updated redirect links

- docs/data-warehouse-integrations/azure-synapse.mdx
> Fixes to the Azure Synapse doc as pointed by @saramashfej [here](https://github.com/rudderlabs/rudderstack-docs/pull/600#discussion_r884949517).
> [Azure Synapse fixes](https://www.notion.so/rudderstacks/Azure-Synapse-fixes-ef55df7682754df2b730fb46d5cd6b6c)
> Azure Synapse fixes

- docs/destinations/attribution/adjust.mdx
> Updated steps for Adjust docs.
> [Updated Adjust steps for Android](https://www.notion.so/rudderstacks/Update-Adjust-docs-for-Android-2fafceaf8cb440728269df3a1d286f1e)
> Adjust documentation updates

- docs/destinations/analytics/singular.mdx
> Singular iOS v2 device mode updates
> [Singular iOS v2 device mode updates](https://www.notion.so/rudderstacks/Singular-device-mode-updates-4340707a42884edba22ee93dc58337da)
> Singular iOS v2 device mode updates

- docs/destinations/attribution/adjust.mdx
> Adjust iOS v2 device mode integration steps
> [Adjust iOS v2](https://www.notion.so/rudderstacks/Documentation-Update-Adjust-Device-Mode-37ec1bd61b86482c920e0a5f96aa1322)
> Adjust device mode integration for iOS v2

- docs/destinations/continuous-integration/appcenter.mdx
> Device mode integration for iOS v2
> [App Center device mode updates](https://www.notion.so/rudderstacks/App-Center-device-mode-updates-69773888d2d5408ea6e52eb18105e33d)
> App Center device mode integration steps for iOS v2

- src/utils/common.js
> Fix [#1]() 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202398365512623
> Convert h1 to text

- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> iOS v2 push notifications support
> [Push notifications iOS v2](https://www.notion.so/rudderstacks/Push-Notifications-iOS-v2-2c042ae2e2f24011b51185e8dea38b14)
> iOS v2 push notifications support

- docs/cloud-extract-sources/netsuite.mdx
- docs/user-guides/administrators-guide/event-replay.mdx
Minor content changes
> Fix [#1]()
> Netsuite and Event Replay: Minor content changes

- docs/destinations/marketing/customer.io.mdx
> Added information on device removal on Application Uninstalled lifecycle event.
> Minor standardization fixes
> [Customer.io doc updates](https://www.notion.so/rudderstacks/Customer-io-doc-updates-4607ffd5d96b42139c7bb8e464c701c5)
> Customer.io documentation updates

- README.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk/flutter-v1.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/index.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ruby-sdk.mdx
- docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-rust-sdk.mdx
- docs/user-guides/administrators-guide/okta-sso.mdx
Updates the last of the GitHub badge links per the new component in  #662
> GH Badge cleanup

- docs/data-governance/tracking-plans/index.mdx
- docs/data-warehouse-integrations/warehouse-schemas.mdx
- docs/rudderstack-api/tracking-plan-api
- docs/rudderstack-api/tracking-plan-api.mdx
- src/postNavList.js
- src/sidebar.js
Create tracking plan API doc
> Fix [#1]()
> Tracking plan API doc

- src/@rocketseat/gatsby-theme-docs/components/NestedAccordion.js
Fixes the behavior where the left navigation pushes all the way down when scrolled
Hat tip @avinder-red-crackle 😄
> fix jumpy navigation

- docs/destinations/advertising/yahoo-dsp.mdx
Added rate limit for requests
> Fix [#1]()
> Yahoo DSP: Added rate limit for requests

- src/sidebar.js
> Get started - sidebar updates

- docs/features/data-governance/index.mdx
- docs/features/data-governance/rudder-typer.mdx
- docs/features/data-governance/ruddertyper.mdx
- docs/features/data-governance/tracking-plans/index.mdx
- docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
- docs/features/identity-resolution.mdx
- docs/features/transformations.mdx
> New nav - Features

- docs/reverse-etl/databricks.mdx
> Added note that the doc covers steps for Azure and that info on other cloud providers will be added soon.
> [Databricks hotfix](https://www.notion.so/rudderstacks/Databricks-Hotfix-b48e1a77c68e4733ae64a44bd3b91440)
> Databricks RETL hotfix

- docs/destinations/analytics/amplitude.mdx
> Made a formatting hotfix for Amplitude destination doc to prevent build/deploy failures.
> Amplitude doc formatting hotfix

- docs/reverse-etl/databricks.mdx
> Databricks: Generic cloud platform

- docs/index.mdx
- docs/tmp-get-started/cloud-vs-open-source.mdx
- docs/tmp-get-started/quickstart.mdx
- docs/tmp-get-started/rudderstack-cloud.mdx
- docs/tmp-get-started/rudderstack-open-source/control-plane-lite.mdx
- docs/tmp-get-started/rudderstack-open-source/data-plane-setup/developer-machine-setup.mdx
- docs/tmp-get-started/rudderstack-open-source/data-plane-setup/docker.mdx
- docs/tmp-get-started/rudderstack-open-source/data-plane-setup/index.mdx
- docs/tmp-get-started/rudderstack-open-source/data-plane-setup/kubernetes.mdx
- docs/tmp-get-started/rudderstack-open-source/index.mdx
- docs/tmp-get-started/rudderstack-open-source/sending-test-events.mdx
- docs/tmp-get-started/what-is-rudderstack.mdx
- docs/user-guides/administrators-guide/index.mdx
> Internal linking: Getting started

- docs/dashboard-guides/audit-logs.mdx
- docs/dashboard-guides/destinations.mdx
- docs/dashboard-guides/live-events.mdx
- docs/dashboard-guides/overview.mdx
- docs/dashboard-guides/personal-access-token.mdx
- docs/dashboard-guides/sources.mdx
- docs/dashboard-guides/teammates.mdx
> Internal Linking: Dashboard guide

- docs/features/data-governance/index.mdx
- docs/features/data-governance/ruddertyper.mdx
- docs/features/data-governance/tracking-plans/index.mdx
- docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
- docs/features/identity-resolution.mdx
- docs/features/transformations.mdx
> Internal Linking: Features

- docs/event-spec/application-lifecycle-events-spec.mdx
- docs/event-spec/ecommerce-events-spec/browsing.mdx
- docs/event-spec/ecommerce-events-spec/coupons.mdx
- docs/event-spec/ecommerce-events-spec/ordering.mdx
- docs/event-spec/ecommerce-events-spec/promotions.mdx
- docs/event-spec/ecommerce-events-spec/reviewing.mdx
- docs/event-spec/ecommerce-events-spec/sharing.mdx
- docs/event-spec/ecommerce-events-spec/wishlisting.mdx
- docs/event-spec/standard-events/alias.mdx
- docs/event-spec/standard-events/common-fields.mdx
- docs/event-spec/standard-events/group.mdx
- docs/event-spec/standard-events/identify.mdx
- docs/event-spec/standard-events/index.mdx
- docs/event-spec/standard-events/page.mdx
- docs/event-spec/standard-events/screen.mdx
- docs/event-spec/standard-events/track.mdx
- docs/event-spec/video-events-spec.mdx
> Internal Linking: Event specification

- docs/resources/community.mdx
- docs/resources/faq.mdx
- docs/resources/glossary.mdx
- docs/resources/rudderstack-architecture.mdx
> Internal Linking: Resources

- netlify.toml
> Testing autogeneration of redirect links
> Netlify redirects

- docs/data-warehouse-integrations/json-column-support.mdx
> Minor changes to the JSON column support doc
> JSON Column Support minor fixes

- docs/destinations/streaming-destinations/amazon-s3.mdx
- docs/destinations/streaming-destinations/kustomer.mdx
- docs/destinations/streaming-destinations/singular/singular-cloud-mode.mdx
- docs/destinations/streaming-destinations/yahoo-dsp.mdx
- docs/destinations/warehouse-destinations/bigquery.mdx
- docs/destinations/warehouse-destinations/json-column-support.mdx
- docs/destinations/warehouse-destinations/postgresql.mdx
- docs/destinations/warehouse-destinations/redshift.mdx
- docs/destinations/warehouse-destinations/snowflake.mdx
- docs/sources/cloud-apps/auth0.mdx
- docs/sources/reverse-etl/databricks.mdx
- src/sidebar.js
> PR containing the changes in the recently merged PRs (which were merged in the old information architecture)
> Changes in the recently merged PRs

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
> Added FAQ re: realtime view and a note regarding the S2S integration.
> GA4 documentation updates

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> Info on the identify call was missing on ga4 pages
> formatting, adding back missing identify information

- src/sidebar.js
> removes the unused `key` property from sidebar.json
> remove key key from sidebar.json

- docs/dashboard-guides/overview.mdx
- docs/sources/reverse-etl/common-settings/sync-modes.mdx
- docs/user-guides/administrators-guide/rudderstack-grafana-dashboard.mdx
- src/postNavList.js
- src/sidebar.js
> Addresses bug fixes and minor doc updates
> [Google Ads Remarketing Lists Mirror Mode update](https://www.notion.so/rudderstacks/Add-FB-Custom-Audience-Mirror-Mode-note-a0ac00da1a0a4e238faeb4e8244716c5)
> [Grafana dashboard doc glitches](https://www.notion.so/rudderstacks/Grafana-dashboard-updates-f4babcd3c74e4ae4ba7af4a039c29297)
> [Dashboard guide overview formatting fixes](https://www.notion.so/rudderstacks/Dashboard-guide-overview-formatting-fixes-8d7a4a12a9154ef780e33674e2bf63b6)
> Minor documentation updates and bug fixes

- docs/sources/sdks/rudderstack-javascript-sdk/consent-managers/index.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/faq.mdx
https://www.notion.so/rudderstacks/Consent-Manager-FAQ-5d05bd0fcb0b4b2bad6cef1350250252
> Fix [#1]()
> Consent Manager FAQ

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Added page call property mappings
https://www.notion.so/rudderstacks/GA4-Cloud-Mode-add-page-properties-for-page-call-996d5959d5d24c379e860709f91787d4
> Fix [#1]()
> GA4 page call property mappings

- docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-mobile-device-mode.mdx
- docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-web-device-mode.mdx
- docs/destinations/streaming-destinations/adobe-analytics/e-commerce-events.mdx
- docs/destinations/streaming-destinations/dcm-floodlight/dcm-floodlight-cloud-mode.mdx
- docs/destinations/streaming-destinations/dcm-floodlight/dcm-floodlight-device-mode.mdx
- docs/destinations/streaming-destinations/drip/drip-cloud-mode.mdx
- docs/destinations/streaming-destinations/drip/drip-web-device-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
- docs/destinations/streaming-destinations/profitwell/profitwell-cloud-mode.mdx
- docs/destinations/streaming-destinations/profitwell/profitwell-web-device-mode.mdx
- docs/destinations/streaming-destinations/singular/singular-cloud-mode.mdx
- docs/destinations/streaming-destinations/singular/singular-device-mode.mdx
> Title updates

- docs/sources/index.mdx
- docs/sources/reverse-etl/index.mdx
- src/data/sources.yaml
> Removed Xero
> Added entries for Snowflake and Databricks in the landing page
[Add links for Snowflake and Databricks in landing pages](https://www.notion.so/rudderstacks/Add-landing-page-links-for-Snowflake-and-Databricks-cd1cdd4f5af94ea78ffb7e3c42c35398)
> Sources landing page updates

- docs/api/index.mdx
- docs/dashboard-guides/index.mdx
- docs/event-spec/index.mdx
- docs/features/index.mdx
- docs/get-started/index.mdx
- docs/resources/index.mdx
- docs/user-guides/index.mdx
- netlify.toml
- Adds index pages in directories where they did not exist
- Adds redirects based on Google Search Console & Google Analytics errors
> URL cleanup

- docs/get-started/rudderstack-open-source/data-plane-setup/docker.mdx
> Docker setup updates
> Fix [#1]()
> Docker setup doc update

- docs/event-spec/video-events-spec.mdx
> Changed the field `action` to `type`.
> Video event spec documentation update

- docs/destinations/warehouse-destinations/faq.mdx
- docs/destinations/warehouse-destinations/warehouse-schema.mdx
Added an FAQ and a note:
https://www.notion.so/rudderstacks/RS-drops-non-standard-columns-declared-at-top-level-of-an-event-144bb9a342de4f0aabc6eca2e0739a60
> Non standard properties FAQ

- docs/destinations/streaming-destinations/snap-pixel.mdx
Minor content fix in the Snap Pixel documentation.
All thanks to @ishachopra0401.
> Minor content updates in Snap Pixel doc

- src/components/DocsNavigation.js
Changes the top nav home link to docs home. This may not be test-able in staging due to the docs path 😬 
> Add a link to the Notion ticket.
> home »» docs home

- src/components/DocsNavigation.js
> remove docs path from link
> Add a link to the Notion ticket.
> remove docs path

- docs/destinations/streaming-destinations/tiktok-ads.mdx
> Updated event and property mappings for Tik Tok Ads
> TikTok Ads updates

- docs/get-started/quickstart.mdx
- docs/sources/cloud-apps/index.mdx
> Minor addition in source types

- docs/destinations/streaming-destinations/mixpanel.mdx
Added Mixpanel FAQ describing API requests size limit
> Added Mixpanel FAQ 

- docs/destinations/streaming-destinations/onesignal.mdx
> Minor suggestions re: OneSignal focusing on the `identify` section
> Minor suggestions re: OneSignal doc

- src/postNavList.js
- src/sidebar.js
> Self-hosted to RS-hosted data plane

- docs/destinations/webhooks.mdx
> Webhook intro update

- CONTRIBUTING.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/detecting-adblocked-pages.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/faq.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/index.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/javascript-sdk-enhancements.mdx
- docs/sources/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
Updates links to current url patterns.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202700609290540
> Update links to remove old docs subdomain reference

- .eslintrc
- .prettierignore
- .prettierrc
- package.json
- yarn.lock
Relicates the eslint and prettier configs the web team use in the main site repo.
> Replicate eslint & prettier configs from main site repo.

- docs/destinations/streaming-destinations/gainsight.mdx
- docs/destinations/warehouse-destinations/delta-lake.mdx
- docs/event-spec/ecommerce-events-spec/index.mdx
- docs/sources/extract/salesforce/index.mdx
> Image and URL fixes

- src/@rocketseat/gatsby-theme-docs/components/Layout/styles.js
- src/css/docs.css
1) Reduce spacing between headers (H2, H3, H4)
2) Make hyperlink text less bold and no-underline
3) Add link color to parameter text in backcticks
> Minor style updates

- docs/get-started/cloud-vs-open-source.mdx
> Incorporate the feedback for the OSS vs Cloud doc as suggested by various stakeholders
> Incorporated RS Open Source vs Cloud feedback

- docs/features/identity-resolution.mdx
> Added note to contact CSR to enable ID resolution
> Added ID resolution note

- docs/destinations/streaming-destinations/posthog.mdx
> Added updated property mappings for the PostHog destination.
> Some minor cosmetic updates
> PostHog documentation updates

- docs/event-spec/standard-events/alias.mdx
> Updated `alias` spec to add some missing details.
> Alias call updates

- docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
Explain a permissions issue that causes Google Ads Enhanced Conversions calls to disable the integration
> GA enhanced conversions perms update

- docs/sources/extract/mixpanel-v2.mdx
> Added note re: support for paid Mixpanel plans.
> Added Mixpanel extract note

- docs/destinations/streaming-destinations/hubspot-v2.mdx
- docs/destinations/streaming-destinations/hubspot.mdx
- src/data/destinations.yaml
- src/postNavList.js
- src/sidebar.js
Clarified version details in HubSpot docs
> Hubspot version details update

- docs/destinations/warehouse-destinations/azure-datalake.mdx
- docs/destinations/warehouse-destinations/azure-synapse.mdx
- docs/destinations/warehouse-destinations/bigquery.mdx
- docs/destinations/warehouse-destinations/clickhouse.mdx
- docs/destinations/warehouse-destinations/delta-lake.mdx
- docs/destinations/warehouse-destinations/gcs-datalake.mdx
- docs/destinations/warehouse-destinations/postgresql.mdx
- docs/destinations/warehouse-destinations/redshift.mdx
- docs/destinations/warehouse-destinations/s3-datalake.mdx
- docs/destinations/warehouse-destinations/snowflake.mdx
- docs/destinations/warehouse-destinations/sql-server.mdx
- src/components/iplist.js
Created Iplist component to render common content under 'IPs to be allowlisted' section
* H2 section does not appear in the contents bar :(
> Add <Iplist/> component

- docs/destinations/warehouse-destinations/azure-datalake.mdx
- docs/destinations/warehouse-destinations/azure-synapse.mdx
- docs/destinations/warehouse-destinations/bigquery.mdx
- docs/destinations/warehouse-destinations/clickhouse.mdx
- docs/destinations/warehouse-destinations/delta-lake.mdx
- docs/destinations/warehouse-destinations/gcs-datalake.mdx
- docs/destinations/warehouse-destinations/postgresql.mdx
- docs/destinations/warehouse-destinations/redshift.mdx
- docs/destinations/warehouse-destinations/s3-datalake.mdx
- docs/destinations/warehouse-destinations/snowflake.mdx
- docs/destinations/warehouse-destinations/sql-server.mdx
- src/@rocketseat/gatsby-theme-docs/components/Docs/index.js
- src/components/iplist.js
Created Iplist component to render common content under 'IPs to be allowlisted' section
> IP list component (Take II)

- src/@rocketseat/gatsby-theme-docs/components/Layout/styles.js
> Test PR to widen the main content pane.
> Widen main content column

- docs/destinations/warehouse-destinations/faq.mdx
> Added warehouse FAQ on avoid column count limit in warehouse tables.
> Column count threshold FAQ update

- docs/get-started/rudderstack-open-source/data-plane-setup/docker.mdx
- docs/get-started/rudderstack-open-source/data-plane-setup/index.mdx
> Updated commands and examples for the Docker setup and data plane health checks as per feedback by Pradeep
> Data Plane Setup command updates

- docs/destinations/streaming-destinations/amplitude.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
> Ported the changes from [this PR](https://github.com/rudderlabs/rudderstack-docs/pull/677/files) which somehow seem to be missing in the doc.
> Amplitude group call updates

- docs/destinations/streaming-destinations/fb-pixel.mdx
Added note for passing external ID in FB Pixel
> FB Pixel update

- src/postNavList.js
- src/sidebar.js
Moved Shynet to Analytics section
> Shynet sidebar update

- docs/destinations/streaming-destinations/dcm-floodlight/index.mdx
- docs/destinations/streaming-destinations/dcm-floodlight/setting-up-dcm-floodlight-in-rudderstack.mdx
> Added note related to the time required for the events to reflect in DCM Floodlight.
> DCM Floodlight Note

- docs/get-started/what-is-rudderstack.mdx
Update What is RudderStack page
> add reference to real-time events

- docs/destinations/streaming-destinations/index.mdx
Section to list the web device mode supported destinations
> Web device mode listing

- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
Added a section to sett external ID in JS SDK
> Setting external ID in JS SDK

- docs/destinations/streaming-destinations/aws-personalize.mdx
> Added a long-lost note in the AWS Personalize doc. Card [here](https://www.notion.so/rudderstacks/Personalize-Doc-Update-63891da634834f3fa2aea9047d176d6e).
> AWS Personalize note

- docs/destinations/warehouse-destinations/azure-datalake.mdx
- docs/destinations/warehouse-destinations/azure-synapse.mdx
- docs/destinations/warehouse-destinations/bigquery.mdx
- docs/destinations/warehouse-destinations/clickhouse.mdx
- docs/destinations/warehouse-destinations/delta-lake.mdx
- docs/destinations/warehouse-destinations/faq.mdx
- docs/destinations/warehouse-destinations/gcs-datalake.mdx
- docs/destinations/warehouse-destinations/postgresql.mdx
- docs/destinations/warehouse-destinations/redshift.mdx
- docs/destinations/warehouse-destinations/s3-datalake.mdx
- docs/destinations/warehouse-destinations/snowflake.mdx
- docs/destinations/warehouse-destinations/sql-server.mdx
- docs/destinations/warehouse-destinations/warehouse-schema.mdx
> Added FAQ re: `rudder_discards` in the BigQuery doc and WH FAQ doc.
> Added FAQ related to rudder_discards

- docs/destinations/streaming-destinations/rockerbox/rockerbox-cloud-mode.mdx
> Update Rockerbox mappings

- docs/destinations/streaming-destinations/tiktok-ads.mdx
> Added phone number FAQ to TikTok docs

- docs/sources/event-streams/cloud-apps/braze-currents.mdx
> Added new event for Braze Currents

- docs/sources/event-streams/cloud-apps/iterable.mdx
- src/sidebar.js
> Renamed Iterable EventStream source to Iterable Webhook

- docs/destinations/streaming-destinations/mixpanel.mdx
> Added the service account-related settings and appropriate references.
> I removed the connection setting images as there were way too many settings for this destination.
> Mixpanel documentation updates

- docs/sources/event-streams/sdks/session-tracking/index.mdx
> Added supported SDK versions.
> Updated supported SDK versions in Session tracking

- docs/get-started/rudderstack-open-source/control-plane-lite.mdx
- docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
- docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
- docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
- docs/sources/event-streams/sdks/rudderstack-flutter-sdk/index.mdx
- docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
- docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
- docs/sources/event-streams/sdks/rudderstack-unity-sdk.mdx
> Minor fixes in Control plane lite

- docs/destinations/streaming-destinations/g-ads-gtag.mdx
- docs/destinations/streaming-destinations/reddit-pixel.mdx
- docs/destinations/streaming-destinations/snap-pixel.mdx
* Revamped docs
* Added UI mapping support in Snap Pixel, Reddit Pixel and Google ads
> UI mapping in Snap Pixel, Reddit Pixel and Google ads

- docs/event-spec/standard-events/index.mdx
> Added note in response to the MI thread.
> Note to send large numbers as strings

- docs/api/data-regulation-api.mdx
- docs/destinations/streaming-destinations/amplitude.mdx
- docs/destinations/streaming-destinations/appsflyer.mdx
- docs/destinations/streaming-destinations/clevertap.mdx
- docs/destinations/streaming-destinations/intercom.mdx
- docs/destinations/streaming-destinations/mixpanel.mdx
> Added user deletion support for 3 destinations using the Data Regulation API
> User deletion in AppsFlyer, CleverTap, and Mixpanel

- docs/sources/extract/zendesk-support.mdx
> Added beta label in Zendesk Support
> Extract source patch and other hotfixes

- docs/sources/extract/mixpanel-v2.mdx
> Mixpanel resources update

- docs/features/transformations/index.mdx
> Adds an intro video by @esadek to the Transformations landing page
See [deploy preview](https://deploy-preview-938--rudderstack-docs-staging.netlify.app/features/transformations/)
> Add Transformations Loom video

- docs/user-guides/administrators-guide/event-replay.mdx
Added FAQ on how to replay the event data
> Event Replay FAQ

- CONTRIBUTING.mdx
- README.mdx
> Reflects new build process for docs, now that we do not require internal keys to build
> Update README and Contributing guide

- docs/sources/event-streams/sdks/session-tracking/index.mdx
Clarified session_id reference for Amplitude doc.
> Session ID in Amplitude

- docs/destinations/streaming-destinations/clevertap.mdx
Added support for alias call in Clevertap
> Clevertap alias call support

- docs/destinations/streaming-destinations/google-analytics-ga.mdx
> GA: Missing info

- docs/destinations/streaming-destinations/adjust.mdx
- docs/destinations/streaming-destinations/amplitude.mdx
- docs/destinations/streaming-destinations/appcenter.mdx
- docs/destinations/streaming-destinations/braze.mdx
- docs/destinations/streaming-destinations/firebase.mdx
- docs/destinations/streaming-destinations/leanplum.mdx
> Documentation for Flutter Device Mode across the destinations Adjust, Amplitude, Appcenter, Braze, Firebase, Leanplum
> Documentation for Flutter Device Mode

- vercel.sh
Adds shell script for Vercel deployments
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203229285397725
> Prefix paths on main branch builds only

- docs/destinations/streaming-destinations/braze.mdx
Added setting to track anonymous users
> Braze doc update

- docs/destinations/streaming-destinations/fb-offline-conversions.mdx
content_type enhancement in FB Offline Conversions
> content_type enhancement in FB Offline Conversions

- docs/user-guides/migration-guides/index.mdx
- docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> Snowplow doc enhancements

- docs/destinations/streaming-destinations/braze.mdx
> Added iOS v2 device mode updates for Braze.
> Braze iOS v2 device mode updates

- docs/destinations/streaming-destinations/freshmarketer.mdx
Added Track and Group call updates
> Freshmarketer updates

- docs/destinations/streaming-destinations/freshsales.mdx
> Freshsales updates

- vercel.json
> Remove circular redirect

- docs/user-guides/administrators-guide/okta-sso.mdx
> Added note re: installing the Okta SSO integration through OIN.
> Okta SSO updates

- docs/event-spec/ecommerce-events-spec/browsing.mdx
- docs/event-spec/ecommerce-events-spec/coupons.mdx
- docs/event-spec/ecommerce-events-spec/ordering.mdx
- docs/event-spec/ecommerce-events-spec/promotions.mdx
- docs/event-spec/ecommerce-events-spec/reviewing.mdx
- docs/event-spec/ecommerce-events-spec/sharing.mdx
- docs/event-spec/ecommerce-events-spec/wishlisting.mdx
> Fixed some code snippets to have double quotes instead of single quotes to reduce confusion.
> Ecommerce spec code formatting hotfix

- docs/api/data-regulation-api.mdx
- docs/destinations/streaming-destinations/amplitude.mdx
- docs/destinations/streaming-destinations/appsflyer.mdx
- docs/destinations/streaming-destinations/braze.mdx
- docs/destinations/streaming-destinations/clevertap.mdx
- docs/destinations/streaming-destinations/intercom.mdx
- docs/destinations/streaming-destinations/mixpanel.mdx
Updated docs for mandatory userID parameter
> Suppress delete api updates

- docs/features/data-governance/tracking-plans/tracking-plan-spreadsheet.mdx
> Added a note describing how to make a copy of the tracking plan spreadsheet to avoid any authorization/security issues.
> Reference/Thread: https://rudderlabs.slack.com/archives/C03DBFDH9CP/p1667926076602089?thread_ts=1667857610.700499&cid=C03DBFDH9CP
> Tracking Plan spreadsheet update

- docs/destinations/streaming-destinations/zendesk.mdx
> Added info re: adding user's primary email in Zendesk
> Zendesk identify call update

- docs/destinations/streaming-destinations/klaviyo.mdx
> Updated some e-commerce property mappings
> Made some minor standardization fixes
> Formatting fixes for info blocks
Doc preview: https://rudderstack-docs-p2wzthopc-rudder-stack.vercel.app/
> Klaviyo e-commerce event mapping update

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Updated doc with GA4 client_id information
> GA4 client_id

- docs/sources/reverse-etl/amazon-s3.mdx
> Amazon S3 update

- docs/destinations/streaming-destinations/clevertap.mdx
Updated doc to add conversion of objects and arrays to string
> Clevertap updates

- docs/features/transformations/device-mode-transformations.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
- docs/user-guides/how-to-guides/self-hosting-js-sdk.mdx
> JS SDK load options

- docs/destinations/streaming-destinations/pinterest-ads/setting-up-pinterest-ads.mdx
Updated event name in Pinterest
> Pinterest doc update

- docs/destinations/warehouse-destinations/faq.mdx
> Added warehouse FAQ on the automatic type conversions supported by RudderStack
> Add Warehouse FAQ

- docs/sources/event-streams/sdks/session-tracking/index.mdx
> Merged two rows re: `startSession()` method and clarified the related information.
> Session tracking table formatting fix

- docs/destinations/streaming-destinations/appcenter.mdx
- docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> Updated App Center's Android device mode version from `1.0.0` to `1.+`.
> App Center Android device mode version update

- docs/event-spec/standard-events/common-fields.mdx
> Updated contextual fields section to clarify the automatically collected fields vs. the ones that are not automatically collected.
> Contextual fields section update

- docs/destinations/streaming-destinations/campaign-manager-360.mdx
- src/data/destinations.yaml
- src/postNavList.js
- src/sidebar.js
Created doc for Campaign Manager 360 destination
Preview link: https://rudderstack-docs-git-dcm-offline-conversion-rudder-stack.vercel.app/destinations/streaming-destinations/campaign-manager-360/
> Campaign Manager 360

- docs/destinations/streaming-destinations/sendgrid.mdx
Added identify call and support for deletion
> Sendgrid updates

- gatsby-config.js
- package.json
- yarn.lock
This reverts commit edec22a1bdf1fdaa274894e912a8495b8d4ed21c. This appears to be an unintentional change that broke builds. @pfd to confirm.
> Revert "finish up glossary poc"

- docs/destinations/streaming-destinations/mixpanel.mdx
- docs/destinations/streaming-destinations/serenytics.mdx
> Mixpanel group call updates

- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
Updated config options in Gatsby guide
> Config options in Gatsby guide

- docs/destinations/warehouse-destinations/faq.mdx
- docs/destinations/warehouse-destinations/warehouse-schema.mdx
> Added an FAQ clarifying that RS honors the customer's WH schema for all WH destinations.
> Warehouse Schema FAQ updates

- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-gatsby-integration.mdx
> Config options updated in gatsby doc
> Gatsby config updated

- docs/destinations/streaming-destinations/mixpanel.mdx
- docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
- docs/sources/event-streams/cloud-apps/refiner.mdx
Adds integration videos for:
- Refiner Source: https://rudderstack-docs-git-videos-rudder-stack.vercel.app/sources/event-streams/cloud-apps/refiner/
- Refiner Cloud Mode: https://rudderstack-docs-git-videos-rudder-stack.vercel.app/destinations/streaming-destinations/refiner/refiner-cloud-mode/
- Mixpanel Cloud Mode: https://rudderstack-docs-git-videos-rudder-stack.vercel.app/destinations/streaming-destinations/mixpanel/
> add integration videos

- docs/destinations/streaming-destinations/bingads.mdx
Property mappings update in track call
> Bing Ads doc update

- docs/destinations/streaming-destinations/posthog/posthog-device-mode.mdx
> PostHog device mode doc update

- docs/destinations/streaming-destinations/vwo.mdx
> Standardized the VWO doc with the changes from this [PR](https://github.com/rudderlabs/rudderstack-docs/pull/842):
> VWO doc standardization

- docs/destinations/streaming-destinations/snapchat-custom-audience.mdx
- docs/sources/event-streams/cloud-apps/shopify.mdx
add shopify and snapchat videos
> add shopify and snapchat videos

- docs/destinations/aws-iam-role-for-rudderstack.mdx
- docs/destinations/streaming-destinations/amazon-eventbridge.mdx
- docs/destinations/streaming-destinations/amazon-kinesis-firehose.mdx
- docs/destinations/streaming-destinations/amazon-kinesis.mdx
- docs/destinations/streaming-destinations/amazon-s3.mdx
- docs/destinations/streaming-destinations/aws-lambda.mdx
- docs/destinations/streaming-destinations/aws-personalize.mdx
- docs/destinations/warehouse-destinations/delta-lake.mdx
- docs/destinations/warehouse-destinations/s3-datalake.mdx
- docs/destinations/warehouse-destinations/snowflake.mdx
> Updated note re: access keys-based authentication method in the IAM role doc and the supported destinations.
> Access key based auth deprecation note

- docs/destinations/streaming-destinations/appsflyer.mdx
> Added missing dashboard settings in the AppsFlyer doc.
> Some minor doc cleanup and standardization.
> Appsflyer doc hotfix

- docs/destinations/streaming-destinations/tiktok-ads.mdx
> TikTok track call payload update

- docs/destinations/streaming-destinations/appsflyer.mdx
> Updated the AppsFlyer React Native device mode integration
> AppsFlyer doc updates

- docs/features/transformations/device-mode-transformations.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/quick-start-guide.mdx
- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
JS SDK async load snippet updated
> JS SDK async load snippet update

- docs/destinations/streaming-destinations/moengage.mdx
Updated MoEngage Android code snippet
> Update MoEngage Android code snippet

- docs/destinations/streaming-destinations/activecampaign.mdx
Updated reference to find event key
> ActiveCampaign: Updated reference to find event key

- docs/sources/event-streams/sdks/rudderstack-ruby-sdk.mdx
> Updated Ruby SDK documentation

- docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-device-mode.mdx
> Added LDP section in the Pinterest Ads device mode doc
> Pinterest Ads LDP device mode

- docs/destinations/streaming-destinations/braze.mdx
Adds dedupe section in the Braze docs
> add dedupe section

- docs/destinations/streaming-destinations/braze.mdx
Reverts rudderlabs/rudderstack-docs#1100
> Revert "add dedupe section"

- docs/destinations/streaming-destinations/google-adwords-enhanced-conversions.mdx
- docs/destinations/streaming-destinations/google-adwords-offline-conversions.mdx
- src/data/destinations.yaml
> Changed Adwords to Ads in Enhanced Conversions doc
> Updated destinations landing page
> Added FAQ in the Offline Conversions doc with the steps.
> Google Ads doc updates

- docs/destinations/streaming-destinations/braze.mdx
> Revert "Revert "add dedupe section""

- docs/sources/event-streams/sdks/rudderstack-go-sdk.mdx
> Updated the `Gzip` parameter to `DisableGzip`
> Updated SDK version from v4.0.0 to v4.1.0
> Go SDK doc updates

- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> Added load option in JS SDK

- docs/destinations/streaming-destinations/braze.mdx
> Added section on nested array operations.
> Added Braze logging connection setting.
> Moved dedup section under `identify` for better flow of information.
> Minor language fixes and improvements.
> Braze documentation updates

- docs/destinations/streaming-destinations/discord.mdx
- src/data/destinations.yaml
- src/sidebar.js
> Discord destination doc

- docs/sources/event-streams/sdks/rudderstack-flutter-sdk/flutter-v2.mdx
> Automatic screen recording section added.
> Optimized the doc to remove the obviously unnecessary callouts.
> Fixed the language and improved clarity in some sections.
> Flutter SDK updates

- docs/destinations/rudderstack-connection-modes.mdx
> Added FAQ re: use of event forwarding proxy in the device mode.
> Added device mode related FAQ

- docs/destinations/streaming-destinations/adobe-analytics/adobe-analytics-web-device-mode.mdx
- docs/destinations/streaming-destinations/attentive-tag.mdx
- docs/destinations/streaming-destinations/clevertap.mdx
- docs/destinations/streaming-destinations/fb-pixel.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-ga.mdx
- docs/destinations/streaming-destinations/iterable/iterable-cloud-mode.mdx
- docs/destinations/streaming-destinations/ometria.mdx
- docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-cloud-mode.mdx
- docs/destinations/streaming-destinations/pinterest-ads/pinterest-ads-device-mode.mdx
- docs/event-spec/ecommerce-events-spec/index.mdx
- docs/event-spec/ecommerce-events-spec/ordering.mdx
- docs/event-spec/standard-events/track.mdx
- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/supported-api.mdx
- src/sidebar.js
> e-commerce »» ecommerce

- docs/destinations/streaming-destinations/tiktok-ads.mdx
> Removed FAQ from TikTok ads doc

- docs/event-spec/ecommerce-events-spec/ordering.mdx
> Ecommerce field calculations

- docs/sources/event-streams/cloud-apps/auth0.mdx
Added clarity for supported events and property mappings
> Auth0 doc update

- vercel.json
Fixes redirects by updating source paths to match how the main site proxies urls.
> Remove trailing slash from source entries

- docs/sources/event-streams/sdks/rudderstack-react-native-sdk.mdx
> React native SDK updates

- src/components/iplist.js
> Updated allowlist IPs to include regions
> Allowlist IPs update

- docs/destinations/streaming-destinations/axeptio.mdx
- docs/destinations/streaming-destinations/microsoft-clarity.mdx
- docs/destinations/streaming-destinations/satismeter.mdx
- src/data/destinations.yaml
- src/sidebar.js
> Reverted the following destination docs:
- Axeptio
- Satismeter
- Microsoft Clarity
> Reverted destination docs

- docs/index.mdx
> test commit

- docs/destinations/streaming-destinations/axeptio.mdx
- docs/destinations/streaming-destinations/microsoft-clarity.mdx
- docs/destinations/streaming-destinations/satismeter.mdx
- src/data/destinations.yaml
- src/sidebar.js
> Reverted the following destinations:
- Axeptio
- MS Clarity
- Satismeter
> Reverted destinations

- docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
> Rockerbox updates

- docs/sources/event-streams/cloud-apps/auth0.mdx
- docs/sources/event-streams/cloud-apps/pagerduty.mdx
- docs/sources/event-streams/cloud-apps/pipedream.mdx
- docs/sources/event-streams/cloud-apps/satismeter.mdx
> Added videos for Auth0, PagerDuty, Pipedream, and Satismeter
> Added source integration videos

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-device-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
Start on GA4 Hybrid mode updates
> GA4 hybrid mode updates

- docs/destinations/streaming-destinations/optimizely-feature-experimentation/cloud-mode.mdx
- docs/destinations/streaming-destinations/optimizely-feature-experimentation/device-mode.mdx
- docs/destinations/streaming-destinations/optimizely-feature-experimentation/index.mdx
- docs/destinations/streaming-destinations/optimizely-feature-experimentation/setup-guide.mdx
- src/sidebar.js
> Added cloud mode documentation for Optimizely Feature Experimentation (Full Stack)
> Updated and restructured the existing docs for device mode.
> Optimizely Feature Experimentation docs

- docs/destinations/streaming-destinations/mailchimp.mdx
> Track call in Mailchimp doc

- docs/destinations/streaming-destinations/rockerbox/rockerbox-cloud-mode.mdx
- docs/destinations/streaming-destinations/rockerbox/setting-up-rockerbox.mdx
> Revert changes made in PR #1134 
> Added a note in the cloud mode doc.
> Rockerbox revert changes

- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/onetrust-consent-manager.mdx
> Onetrust doc revamp

- docs/destinations/streaming-destinations/criteo-audience.mdx
- src/data/destinations.yaml
- src/sidebar.js
> Criteo audience doc

- docs/destinations/streaming-destinations/lemnisk/index.mdx
- docs/destinations/streaming-destinations/lemnisk/lemnisk-cloud-mode.mdx
- docs/destinations/streaming-destinations/lemnisk/lemnisk-device-mode.mdx
- docs/destinations/streaming-destinations/lemnisk/setting-up-lemnisk.mdx
- src/data/destinations.yaml
- src/sidebar.js
> Lemnisk latest doc

- docs/features/profiles.mdx
> Minor doc updates for the Profiles doc based on user feedback
> Profiles doc updates

- docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration.mdx
> Updated code snippets in Next.js

- docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> JS load option: polyfillIfRequired

- docs/destinations/streaming-destinations/g-ads-gtag.mdx
> Update Google Ads connection settings 

- docs/sources/reverse-etl/snowflake.mdx
> Added role option in Snowflake doc

- docs/destinations/warehouse-destinations/s3-datalake.mdx
> Additional partition permissions for S3 data lake destination.
> S3 data lake Glue partition permissions

- docs/destinations/streaming-destinations/google-analytics-4/google-analytics-4-cloud-mode.mdx
- docs/destinations/streaming-destinations/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> GA4 send_to parameter update

- docs/event-spec/standard-events/identify.mdx
Quick update on the `IDENTIFY` endpoint behaviour.
> fix: identify traits

- CONTRIBUTING.mdx
> CLA form updates

- .npmrc
- .yarnrc
- package.json
- vercel.json
> Disable npm lifecycle hooks in the old Docs repo
> Disable npm lifecycle hooks
